config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: 'devise_overrides/registrations'
  }

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end
  get 'dashboard/ranking'

  resources :games, only: [:index, :new, :create]

  root to: "site#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  # Asociations
  belongs_to :player1, class_name: 'User', foreign_key: 'player1_id'
  belongs_to :player2, class_name: 'User', foreign_key: 'player2_id'

  # Validations
  validates :player1_id, presence: true, numericality: { only_integer: true }
  validates :player2_id, presence: true, numericality: { only_integer: true }
  validates :player1_score, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 21 }
  validates :player2_score, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 21 }
  validate :ping_pong_rules
  validate :cant_play_yourself

  def log_match
    # Calculate ELO ranking update for both users
    match = EloRating::Match.new
    match.add_player(rating: player1.elo_points, winner: wins?(player1))
    match.add_player(rating: player2.elo_points, winner: wins?(player2))
    new_points = match.updated_ratings # => [1988, 2012]

    # Can't update elo points and ranking at once se we need to save the user each time
    player1.update_attributes(elo_points: new_points[0], total_games: player1.total_games + 1, total_wins: player1.total_wins + (wins?(player1) ? 1 : 0))
    player2.update_attributes(elo_points: new_points[1], total_games: player2.total_games + 1, total_wins: player2.total_wins + (wins?(player2) ? 1 : 0))

    # Cache user ranking for better performance
    User.update_rankings!
  end

  def self.user_games(current_user)
    Game.where(player1_id: current_user.id).or(Game.where(player2_id: current_user.id)).includes(:player1, :player2)
  end

  def rival(user)
    self.player1_id == user.id ? player2 : player1
  end

  def rival_score(user)
    self.player1_id != user.id ? player1_score : player2_score
  end

  def user_score(user)
    self.player1_id == user.id ? player1_score : player2_score
  end

  def match_result(user)
    if (player1_score - player2_score).abs < 2
      'D'
    else
      (player1_score > player2_score) == (self.player1_id == user.id) ? 'W' : 'L'
    end
  end

  def wins?(user)
    match_result(user) == 'W'
  end

  protected
  def cant_play_yourself
    if player1_id == player2_id
      errors.add(:player2_id, 'Can not play yourself')
    end
  end

  def ping_pong_rules
    # Clamp values, between 21 and 19, since anything bellow 19 is irrelevant
    sc1 = [player1_score, 19].max
    sc2 = [player2_score, 19].max
    sc = "#{sc1}-#{sc2}"

    # Avoid entangled boolean logic by splitting results into categories and use direct comparison
    # Note: 21-19, 19-21, and 20-20 are the only valid scores
    error_codes = {
      "19-19" => ['player1_score', 'any player needs to reach 21 points or tie'],
      "20-19" => ['player1_score', 'any player needs to reach 21 points or tie'],
      "19-20" => ['player2_score', 'any player needs to reach 21 points or tie'],
      "21-20" => ['player2_score', 'a player must win by a 2 point margin'],
      "20-21" => ['player1_score', 'a player must win by a 2 point margin'],
      "21-21" => ['player1_score', 'players can not tie beyond 20 points']
    }

    if error_codes[sc].present?
      errors.add(error_codes[sc][0].to_sym, error_codes[sc][1])
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Validations
  validates :username, :email, presence: true
  validates :username, :email, uniqueness: true
  validates :username, format: { with: /\A[\w\d-]*\z/ }
  validates :username, length: { in: 3..16 }
  validates :email, format: { with: /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}\z/ }

  # Callbacks
  before_save :format_attributes
  after_create :self_update_rankings!

  def initial
    username[0].upcase
  end

  def self.all_except(user)
    where.not(id: user)
  end

  def win_ratio
    if total_games == 0
      0
    else
      100 * total_wins / total_games
    end
  end

  def self.update_rankings!
    User.find_each(batch_size: 1000) do |user|
      user.update_attributes(elo_ranking: User.order(elo_points: :desc, username: :asc).pluck(:id).index(user.id) + 1)
    end
  end

  def self_update_rankings!
    self.class.update_rankings!
  end

  private
  def format_attributes
    self.username.downcase!
    self.email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  # Filters
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @games = Game.user_games(current_user).order(created_at: :desc).first(3)
    @ranked_users = User.order(:elo_ranking).first(10)
  end

  def ranking
    @ranked_users = User.order(:elo_ranking)
  end
end

app/controllers/devise_overrides/registrations_controller.rb
class DeviseOverrides::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, only: :create

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :load_rivals, only: [:new, :create]
  def index
    @games = Game.user_games(current_user).order(created_at: :desc)
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params.merge(player1_id: current_user.id))
    if @game.save
      @game.log_match
      flash[:alert] = 'Game created successfully'
      redirect_to games_path
    else
      render 'new'
    end
  end

  protected
  def load_rivals
    @rivals = User.all_except current_user
  end
  def game_params
    params.require(:game).permit(:player1_score, :player2_score, :player2_id)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	skip_before_action :authenticate_user!, only: [:index]

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def field_errors(builder, field, aditional_clases = '')
    unless builder.object.errors[field].blank?
      content_tag :div, class: "ui label #{aditional_clases}" do
        content_tag :span, builder.object.errors[field].first.html_safe
      end
    end
  end

  def ranking_text(ranking)
    ranking < 1 ? "N/A" : ranking.ordinalize
  end

  def active_if_current_user(user, current_user)
    user == current_user ? 'active' : ''
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/games_helper.rb
module GamesHelper
  def match_result_color(result)
    case result
    when 'L'
     'red'
    when 'D'
     'grey'
    when 'W'
      'green'
    end
  end
end

app/views/dashboard/index.html.erb
<div id="dashboard-index-content" class="dashboard-content">
  <div class="ui container">
    <div class="ui stacked segment">
      <div class="ui grid">
        <!-- main content -->
        <div class="twelve wide column">
          <h1>
            <a class="ui massive green circular label"><%= current_user.initial %></a> 
            <span class="main-title"><%= current_user.username %></span>
            <span>&middot;</span>
            <%= link_to 'Add new game', new_game_path %>
          </h1>
          <div class="ui statistics">
            <div class="inverted statistic">
              <div class="value">
                <%= ranking_text(current_user.elo_ranking) %>
              </div>
              <div class="label">
                Ranking
              </div>
            </div>
            <div class="statistic">
              <div class="value">
                <%= current_user.elo_points %>
              </div>
              <div class="label">
                Ranking Points
              </div>
            </div>
            <div class="statistic">
              <div class="value">
                <i class="trophy icon"></i>
              </div>
              <div class="label">
                <%= current_user.total_wins %> wins
              </div>
            </div>
            <div class="statistic">
              <div class="value">
                <%= current_user.win_ratio %>%
              </div>
              <div class="label">
                Win ratio
              </div>
            </div>
          </div>

          <h2>
            <span>Your last games</span>
            <span>&middot;</span>
            <%= link_to 'View all', games_path %>
          </h2>
          <% if @games.size > 0 %>
            <div id="user-games" class="ui four cards">
              <%= render 'games/user_games' %>
            </div>
          <% else %>
            <p class="blank">You haven't logged any game yet.</p>
          <% end %>
        </div>

        <!-- sidebar -->
        <div class="four wide column">
          <h2>Current ranking</h2>
          <table class="ui very basic celled table">
            <thead>
              <tr>
                <th>Rank</th>
                <th>User</th>
                <th>Points</th>
              </tr>
            </thead>
            <tbody>
              <% @ranked_users.each do |user| %>
              <tr>
                <td><%= ranking_text(user.elo_ranking) %></td>
                <td><%= user.username %></td>
                <td><%= user.elo_points %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <h4><%= link_to 'See full ranking table', dashboard_ranking_path %></h4>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/ranking.html.erb
<div id="dashboard-ranking-content" class="dashboard-content">
  <div class="ui container">
    <div class="ui stacked segment">
      <h1>Current Ping Pong ranking</h1>
      <table class="ui celled table">
        <thead>
          <tr>
            <th>Rank</th>
            <th>User</th>
            <th>Points</th>
            <th>Played games</th>
            <th>Wins</th>
            <th>Win Ratio</th>
          </tr>
        </thead>
        <tbody>
          <% @ranked_users.each do |user| %>
            <%= content_tag :tr, class: active_if_current_user(user, current_user) do %>
              <td><%= ranking_text(user.elo_ranking) %></td>
              <td><%= user.username %></td>
              <td><%= user.elo_points %></td>
              <td><%= user.total_games %></td>
              <td><%= user.total_wins %></td>
              <td><%= user.win_ratio %></td>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/games/_user_games.html.erb
<% @games.each do |game| %>
<div class="ui card">
  <div class="content">
    <div class="header">
      <%= content_tag :div, class: 'ui horizontal label ' << match_result_color(game.match_result(current_user)) do %>
        <%= game.match_result(current_user) %>
      <% end %>
      <%= game.rival(current_user).username %>
    </div>
    <div class="description">
      <div class="match-result">
        <a class="ui big black label"><%= game.user_score(current_user) %></a> - <span><a class="ui big black label"><%= game.rival_score(current_user) %></a></span></b>
      </div>
    </div>
  </div>
  <div class="extra content">
    <span class="right floated">
      <span><%= time_ago_in_words(game.created_at) %> ago</span>
    </span>
  </div>
</div>
<% end %>

app/views/games/index.html.erb
<div id="games-index-content" class="dashboard-content">
  <div class="ui container">
    <div class="ui stacked segment">
      <h1>
        <span class="main-title">My games</span>
        <span>&middot;</span>
        <%= link_to 'Add new game', new_game_path %>
      </h1>

      <% if @games.size > 0 %>
        <div id="user-games" class="ui five cards">
          <%= render 'user_games' %>
        </div>
      <% else %>
        <p class="blank">You haven't logged any game yet.</p>
      <% end %>      
    </div>
  </div>
</div>

app/views/games/new.html.erb
<div id="games-new-content" class="dashboard-content">
  <div class="ui container">
    <div class="ui stacked segment">
      <h1>Add a new game</h1>
      
      <div class="ui centered grid">
        <%= form_for(@game, html: { method: :post, class: "ui form #{flash[:error].present? ? 'error' : ''}" }) do |f| %>
          <div class="scores">
            <div class="field">
              <%= field_errors f, :player1_score, 'black bottom pointing' %>
              <%= f.text_field :player1_score, placeholder: 0, size: 2  %>
              <label><%= current_user.username %> (you)</label>
            </div>
            <span class="middle">-</span>
            <div class="field">
              <%= field_errors f, :player2_score, 'black bottom pointing' %>
              <%= f.text_field :player2_score, placeholder: 0, size: 2  %>
              <%= field_errors f, :player2_id, 'black top pointing' %>
              <%= f.collection_select :player2_id, @rivals, :id, :username, { include_blank: true }, { class: 'ui search dropdown' } %>
            </div>
          </div>

          <div class="actions">
            <%= f.submit 'Create game', class: 'ui fluid huge blue submit button' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ping Pong</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- main nav menu -->
    <%= render 'shared/menu' %>

    <!-- flash messages -->
    <%= render 'shared/notifications' %>

    <%= yield %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, id: "flash_#{name}", class: 'ui message' do %>
    <%= content_tag :p, msg %>
  <% end %>
<% end %>

app/views/shared/_menu.html.erb
<div class="ui fixed inverted menu">
  <div class="ui container">
    <a href="/" class="header item">
      <%= image_tag asset_path('thick_logo.png'), alt: 'Ping Pong' %>&nbsp;&nbsp;&nbsp;Ping Pong
    </a>

    <% if user_signed_in? %>
      <%= link_to 'My games', games_path, class: 'item' %>
      <%= link_to 'Leaderboard', dashboard_ranking_path, class: 'item' %>      
    <% end %>

    <div class="right menu">
      <% if user_signed_in? %>
        <div class="ui simple dropdown item">
        <%= current_user.username %> <i class="dropdown icon"></i>
        <div class="menu">
          <%= link_to 'Edit profile', edit_user_registration_path, class: 'item' %>
          <%= link_to 'Add new game', new_game_path, class: 'item' %>
          <div class="divider"></div>
          <%= link_to "Logout", destroy_user_session_path, :method => :delete, class: 'item' %> 
        </div>
      <% else %>
        <%= link_to 'Log in', new_user_session_path, class: 'item' %><br />
        <%= link_to 'Sign up', new_user_registration_path, class: 'item' %><br />
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/shared/_notifications.html.erb
<div id="notification-area">
  <% if notice %>
  <div class="ui message">
    <p><%= notice %></p>
  </div>
  <% end %>
  <% if alert %>
  <div class="ui message">
    <p><%= alert %></p>
  </div>
  <% end %>
</div>

app/views/site/index.html.erb
<div id="site-index-content">
  <div class="ui container">
    <div class="tagline">
      <h1>We log your <span>Ping&nbsp;Pong</span> games while you sit back relax</h1>
      <%= link_to 'Sign up now!', new_user_registration_path, class: 'massive ui blue button' %>
    </div>
  </div>
</div>